theme: jekyll-theme-minimal
title: Good Journey
author: Baris854
email: barishsiao854@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am trying hard to learn something from this.
  Wish me luck

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
